name: skibidi_invasion
description: "Hentai Invasion"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  auto_size_text: ^3.0.0
  flutter_tts: ^4.2.2
  animated_toggle_switch: ^0.8.5
  animate_do: ^4.2.0
  just_audio: ^0.10.2
  page_transition: ^2.2.1
  shared_preferences: ^2.5.3
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/bg/
    - assets/images/logo/mem-logo.png
    - assets/icons/brokenheart.png
    - assets/images/characters/
    - assets/images/characters/pose1/
    - assets/images/characters/pose2/
    - assets/images/characters/skibidi/
    - assets/icons/
    - assets/audio/sfx/
    - assets/audio/sfx/emotion/
    - assets/audio/sfx/action/
    - assets/audio/sfx/sound/
    - assets/audio/voice/
    - assets/audio/bgm/
    - assets/images/dialogue/
    - assets/icons/tutorial_arrow.png
    - assets/audio/sfx/emotion/


  fonts:
    - family: JosefinSans
      fonts:
        - asset: assets/fonts/JosefinSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/JosefinSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/JosefinSans-Bold.ttf
          weight: 700

    - family: TacticRound
      fonts:
        - asset: assets/fonts/TacticRound-Bld.ttf
          weight: 800

    - family: IBMPlexMono
      fonts:
        - asset: assets/fonts/IBMPlexMono-regular.ttf
          weight: 400

    - family: Obafen
      fonts:
        - asset: assets/fonts/Obafen-e9jK3.otf
          weight: 400

    - family: PixelMplus
      fonts:
        - asset: assets/fonts/PixelMplus10-Regular.ttf
          weight: 400

    - family: onryou
      fonts:
        - asset: assets/fonts/onryou.TTF

    - family: JKGothic
      fonts:
        - asset: assets/fonts/JKG-M_3.ttf

    - family: MPlus
      fonts:
        - asset: assets/fonts/MPLUSRounded1c-Regular.ttf
          weight: 400

flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#000000"
  fullscreen: true
  image: assets/images/logo/mem-logo.png
  android_gravity: center
  ios_content_mode: center