name: skibidi_invasion
description: "Hentai Invasion"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  audioplayers: ^6.4.0
  auto_size_text: ^3.0.0
  flutter_tts: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/bg/
    - assets/images/characters/
    - assets/images/characters/pose1/
    - assets/images/characters/pose2/
    - assets/icons/
    - assets/images/dialogue/

  fonts:
    - family: JosefinSans
      fonts:
        - asset: assets/fonts/JosefinSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/JosefinSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/JosefinSans-Bold.ttf
          weight: 700

    - family: TacticRound
      fonts:
        - asset: assets/fonts/TacticRound-Bld.ttf
          weight: 800

    - family: IBMPlexMono
      fonts:
        - asset: assets/fonts/IBMPlexMono-regular.ttf
          weight: 400
