name: skibidi_invasion
description: "Stop Asian Hate"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/bg/
    - assets/images/characters/
    - assets/icons/
    - assets/audio/sfx/
    - assets/audio/music/
    - assets/images/dialogue/

  fonts:
    - family: JosefinSans
      fonts:
        - asset: assets/fonts/JosefinSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/JosefinSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/JosefinSans-Bold.ttf
          weight: 700

    - family: TacticRound
      fonts:
        - asset: assets/fonts/TacticRound-Bld.ttf
          weight: 800

    - family: IBMPlexMono
      fonts:
        - asset: assets/fonts/IBMPlexMono-regular.ttf
          weight: 400
